[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Applies stickers to contents
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "card.T.x = self.T.x"
position = "before"
payload = '''
'''
match_indent = true