[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# setting up gem slot
# Card:init()

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.rank = nil"
position = "after"
payload = "self.gem_slot = nil"
match_indent = true