[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Applies stickers to contents
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "card.T.x = self.T.x"
position = "before"
payload = '''
if self.ability.gemslot_empty then
    card.ability.gemslot_empty = self.ability.gemslot_empty
elseif self.ability.gemslot_ruby then
    card.ability.gemslot_ruby = self.ability.gemslot_ruby
end
'''
match_indent = true