[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Emerald Functionality
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "--check the hand first"
position = "before"
payload = '''
for i = 1, #G.hand.highlighted do
    local _card = G.hand.highlighted[i]

    if _card.ability.gemslot_emerald then
        G.E_MANAGER:add_event(Event({
            trigger = 'after',
            delay = 0.1,
            func = function()
                local trandom_m = {
                	G.P_CENTERS.m_stone,
                	G.P_CENTERS.m_steel,
                	G.P_CENTERS.m_glass,
                	G.P_CENTERS.m_gold,
                	G.P_CENTERS.m_bonus,
                	G.P_CENTERS.m_mult,
                	G.P_CENTERS.m_wild,
                	G.P_CENTERS.m_lucky,
                	"NOTHING"
                }

                local random_m = randomSelect(trandom_m)
                if random_m  ~= "NOTHING" then
					_card:set_ability(random_m)
				end

                return true
            end
        }))
    end
end
'''
match_indent = true